@host=http://localhost:4500

//-------------------------------------------------------------------------------
// ROUTES AUTH

### Register
POST {{host}}/register
Content-Type: application/json

{
    "username": "LauraX",
    "firstname": "Laura",
    "lastname": "Khul",
    "email": "laura@gmail.com",
    "password": "123456"
}

### Login
POST {{host}}/login
Content-Type: application/json

{
    "email": "laura@gmail.com",
    "password": "123456"
}

### refreshToken
POST {{host}}/refresh-token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY0Mjk1Mzc1MSwiZXhwIjoxNjQzNTU4NTUxfQ.Ht-2rITNkoqL8zttwZQ1TxPpCeeviRzyZG3RhWo3rKw

//-------------------------------------------------------------------------------
// ROUTES PROPERTIES

### Tous les jeux
GET {{host}}/properties

### Un jeu
GET {{host}}/properties/2

### Nouvelle propriété
POST {{host}}/properties
Content-Type: application/json

{
    "name": "Milles Champddaadaaaasfe test",
    "description": "Une moche maison",
    "capacity": 4,
    "bedrooms_count": 2,
    "beds_count": 4,
    "bathrooms_count": 1,
    "type": "maison",
    "street_number": 70,
    "street_name": "Avenue des champs élysées",
    "zip_code": 75008,
    "city": "Paris",
    "country": "France",
    "week_price": 100,
    "user_id": 1
}

### Mise à jour jeu
PATCH {{host}}/properties
Content-Type: application/json

{
    "id": 1,
    "name": "Mille bonjours",
    "description": "Une jolie maison",
    "capacity": 4,
    "bedrooms_count": 2,
    "beds_count": 4,
    "bathrooms_count": 1,
    "type": "maison",
    "street_number": 11,
    "street_name": "Avenue Stephane Mallarme",
    "zip_code": 75017,
    "city": "Paris",
    "country": "Espagne",
    "latitude": 45.2,
    "longitude": 45.7
}

### Suppression
DELETE {{host}}/boardgames/1


//-------------------------------------------------------------------------------
// ROUTES PROPERTIES IMAGES

### Tous les images de propriétés
GET {{host}}/properties-images

### une image de propriété
GET {{host}}/properties-images/2

### Nouvelle image de propriété
POST {{host}}/properties-images
Content-Type: application/json

{
    "url": "https://www.ouestfrance-immo.com/photo-vente-maison-dinge-35/207/maison-a-vendre-dinge-15716995_1_1633042576_8db11d1850ddca5c28260d2fb3dadb7d.jpg",
    "name": "Milles Borrétfsdarédazfgretdagrerznes",
    "property_id": 2
}

### Mise à jour jeu
PATCH {{host}}/properties-images
Content-Type: application/json

{
    "url": "https://www.ouestfrance-immo.com/photo-vente-maison-dinge-35/207/maison-a-vendre-dinge-15716995_1_1633042576_8db11d1850ddca5c28260d2fb3dadb7d.jpg",
    "name": "Milles Borrétfsdarédazfgretdagrerznes",
    "property_id": 1
}

### Suppression
DELETE {{host}}/properties-images/1