@host=http://localhost:4500

//-------------------------------------------------------------------------------
// ROUTES AUTH

### Register
POST {{host}}/register
Content-Type: application/json

{
    "username": "LauraX2",
    "firstname": "Laura2",
    "lastname": "Khul2",
    "email": "laura2@gmail.com",
    "password": "123456"
}

### Login
POST {{host}}/login
Content-Type: application/json

{
    "email": "johndoe@mail.com",
    "password": "123456"
}

### refreshToken
POST {{host}}/refresh-token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY0Mjk1Mzc1MSwiZXhwIjoxNjQzNTU4NTUxfQ.Ht-2rITNkoqL8zttwZQ1TxPpCeeviRzyZG3RhWo3rKw

//-------------------------------------------------------------------------------
// ROUTES PROPERTIES

### Tous les jeux
GET {{host}}/properties

### Un jeu
GET {{host}}/properties/2

### Nouvelle propriété
POST {{host}}/properties
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY0MzczNDAxNywiZXhwIjoxNjQzNzM0MzE3fQ.8MZCqIMpXGfdj3IGwYyiGL-T8p6Y_hv52rlPjatNE0M
Content-Type: application/json

{
    "name": "Milles champs des champs",
    "description": "Une moche maison",
    "capacity": "4",
    "bedrooms_count": "2",
    "beds_count": "4",
    "bathrooms_count": "1",
    "type": "maison",
    "street_number": "70",
    "street_name": "Avenue des champs élysées",
    "zip_code": "75008",
    "city": "Paris",
    "country": "France",
    "week_price": "100"
}

### Mise à jour propriété
PATCH {{host}}/properties
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTY0MzczMzE5NiwiZXhwIjoxNjQzNzMzNDk2fQ.ufWycTxacuPAam26o2U99cBwZ2kklfpdvX341UfN3c4
Content-Type: application/json

{
    "id": 1,
    "name": "Mille bonjours",
    "description": "Une jolie maison",
    "capacity": 4,
    "bedrooms_count": 2,
    "beds_count": 4,
    "bathrooms_count": 1,
    "type": "maison",
    "street_number": 11,
    "street_name": "Avenue Stephane Mallarme",
    "zip_code": 75017,
    "city": "Paris",
    "country": "Espagne",
    "latitude": 45.2,
    "longitude": 45.7
}

### Suppression
DELETE {{host}}/boardgames/1


//-------------------------------------------------------------------------------
// ROUTES PROPERTIES IMAGES

### Tous les images de propriétés
GET {{host}}/properties-images

### une image de propriété
GET {{host}}/properties-images/2

### Nouvelle image de propriété
POST {{host}}/properties-images
Content-Type: application/json

{
    "url": "https://www.ouestfrance-immo.com/photo-vente-maison-dinge-35/207/maison-a-vendre-dinge-15716995_1_1633042576_8db11d1850ddca5c28260d2fb3dadb7d.jpg",
    "name": "Milles Borrétfsdarédazfgretdagrerznes",
    "property_id": 2
}

### Mise à jour property image
PATCH {{host}}/properties-images
Content-Type: application/json

{
    "url": "https://www.ouestfrance-immo.com/photo-vente-maison-dinge-35/207/maison-a-vendre-dinge-15716995_1_1633042576_8db11d1850ddca5c28260d2fb3dadb7d.jpg",
    "name": "Milles Borrétfsdarédazfgretdagrerznes",
    "property_id": 1
}

### Suppression
DELETE {{host}}/properties-images/1

//-------------------------------------------------------------------------------
// ROUTES USERS

### Tous les users
GET {{host}}/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY0MzYzNjk1NCwiZXhwIjoxNjQzNjM3MjU0fQ.CKVlyqBQbbgi2RkVlz3Z868deWc5YizTOm1ufY4nRN4

### Un user
GET {{host}}/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY0MzYzODI2OCwiZXhwIjoxNjQzNjM4NTY4fQ.yXAoe6pZIJn0rElBz7QrSD-XoLmBchU2tFuU06j1oEg

### Mise à jour user
PATCH {{host}}/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY0MzYzODk5OSwiZXhwIjoxNjQzNjM5Mjk5fQ.-qUWkeoe0N_5gbSQOBWII3fooIU8YYQrAArkjeQosQU
Content-Type: application/json

{
    "username": "LauraX3",
    "firstname": "Laura3",
    "lastname": "Khul3",
    "email": "laura4@gmail.com",
    "password": "123456"
}

### Suppression
DELETE {{host}}/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsImlhdCI6MTY0MzYzNzE4OCwiZXhwIjoxNjQzNjM3NDg4fQ.ho8ESlQiQFppL-0rHN2zKUlsVrzbB1D2Hfpiu9gH3zM
